import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: 150,
    height: 250,
    position: 'relative',
    marginBottom: 20,
  },
 
  forcaBase: {
    height: 5,
    width: 120,
    backgroundColor: '#fff', 
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  forcaPoste: {
    height: 250,
    width: 5,
    backgroundColor: '#fff', 
    position: 'absolute',
    bottom: 0,
    left: 20,
  },
  forcaViga: {
    height: 5,
    width: 100,
    backgroundColor: '#fff', 
    position: 'absolute',
    top: 0,
    left: 20,
  },
  forcaCorda: {
    width: 5,
    height: 40,
    backgroundColor: '#fff', 
    position: 'absolute',
    top: 0,
    right: 25,
  },
 
  cabeca: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#fff', 
    position: 'absolute',
    top: 40,
    right: 6,
  },
  corpo: {
    width: 4,
    height: 70,
    backgroundColor: '#fff', 
    position: 'absolute',
    top: 80,
    right: 24,
  },
  bracoDireito: {
    width: 40,
    height: 4,
    backgroundColor: '#fff', 
    position: 'absolute',
    top: 100,
    right: -12,
    transform: [{ rotate: '-45deg' }],
  },
  bracoEsquerdo: {
    width: 40,
    height: 4,
    backgroundColor: '#fff', 
    position: 'absolute',
    top: 100,
    right: 20,
    transform: [{ rotate: '45deg' }],
  },
  pernaDireita: {
    width: 50,
    height: 4,
    backgroundColor: '#fff', 
    position: 'absolute',
    top: 165,
    right: -20,
    transform: [{ rotate: '45deg' }],
  },
  pernaEsquerda: {
    width: 50,
    height: 4,
    backgroundColor: '#fff', 
    position: 'absolute',
    top: 165,
    right: 15,
    transform: [{ rotate: '-45deg' }],
  },
});

